name: upload_largest_files
description: A flutter web plugin to upload largest files in web.
version: 0.0.2
homepage: https://github.com/emirdeliz/upload_largest_files

environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: '>=2.5.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    # These assets are compiled from the project Upload largest files.
    # https://github.com/emirdeliz/upload-largest-files.
    - assets/
  plugin:
    platforms:
      web:
        pluginClass: UploadLargestFilesPlugin
        fileName: upload_largest_files_plugin.dart
