name: Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: cirrusci/flutter
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          submodules: recursive
      - uses: abhi1693/setup-browser@v0.3.4
        with:
          browser: chrome
          version: latest
      - run: sh example/scripts/run-integration-test.sh
