name: Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: cirrusci/flutter
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          submodules: recursive
      - uses: browser-actions/setup-chrome@latest
      - run: chrome --version
      - run: CHROMIUM_BIN=$(which chrome) sh example/scripts/run-integration-test.sh
