name: Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-20.04
    container:
      image: cirrusci/flutter

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          submodules: recursive
      - run: |
          sudo apt-get update
          sudo apt-get install -y libgconf-2-4 libatk1.0-0 libatk-bridge2.0-0 libgdk-pixbuf2.0-0 libgtk-3-0 libgbm-dev libnss3-dev libxss-dev libasound2
      - uses: browser-actions/setup-chrome@latest
      - run: chrome --version
      - run: CHROMIUM_BIN=$(which chrome) sh example/scripts/run-integration-test.sh
