name: Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: cirrusci/flutter
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          submodules: recursive
      - uses: actions/checkout@v2
      - uses: nanasess/setup-chromedriver@v1
      - run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
      - run: sh example/scripts/run-integration-test.sh
